### ISSUE TITLE
Build failure: static resource folder edgecase

### ISSUE THREAD

**Issue by PrestonSam** [MarkPflug/Sylvan.BuildTools.Resources#19]
Build fails with the following project layout:

### my-project.csproj
```xml
  ...
  <ItemGroup>
    <StaticResourceFolder Include="data/Example"/>
  </ItemGroup>
  ...
```

### Folder structure
**project-root/data/Example/**
 - file.json
 - otherfile.json
 - Subfolder/

The json files simply have `{}` inside them

### Build fail output
```shell
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(68,25): error CS0756: A partial method may not have multiple defining declarations [/home/sam/.../my-project.csproj]
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(60,2): error CS0579: Duplicate 'global::System.Diagnostics.DebuggerNonUserCode' attribute [/home/sam/.../my-project.csproj]
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(68,25): error CS0111: Type 'Example.Subfolder' already defines a member called 'PreProcess' with the same parameter types [/home/sam/.../my-project.csproj]
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(70,19): error CS0111: Type 'Example.Subfolder' already defines a member called 'Process' with the same parameter types [/home/sam/.../my-project.csproj]

Build FAILED.

/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(68,25): error CS0756: A partial method may not have multiple defining declarations [/home/sam/.../my-project.csproj]
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(60,2): error CS0579: Duplicate 'global::System.Diagnostics.DebuggerNonUserCode' attribute [/home/sam/.../my-project.csproj]
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(68,25): error CS0111: Type 'Example.Subfolder' already defines a member called 'PreProcess' with the same parameter types [/home/sam/.../my-project.csproj]
/home/sam/.../obj/Debug/net7.0/SylvanStaticResources/data/Example.g.cs(70,19): error CS0111: Type 'Example.Subfolder' already defines a member called 'Process' with the same parameter types [/home/sam/.../my-project.csproj]
    0 Warning(s)
    4 Error(s)
```

**Comment by PrestonSam** [comment]
Hi Mark,

Thanks for taking the time to look into this :)

I think that 
```xml
  ...
  <ItemGroup>
    <StaticResourceFolder Include="data/Example"/>
  </ItemGroup>
  ...
```
Should yield `Data.Example` as a namespace.

I would also prefer that nested folders would be interpreted as namespaces in their own right.
i.e. the same XML code shown above would also produce the `Data.Example.Subfolder` namespace, as that would would allow me to automatically create complex nested namespaces by simply including the topmost relevant folder.

I agree that both behaviours should be possible to disable with an attribute to prevent the tool from becoming inconvenient in some circumstances, though.

**Comment by PrestonSam** [comment]
Ah! I see!
I was unaware that nested folders were already supported. I should make use of that feature.

But I do agree that the parent folders (up until the project root) should be included in the namespace as it'd isolate all generated classes under a dedicated namespace, reducing the chance of a generated class duplicating the name of a class in the source code.

**Comment by MarkPflug** [comment]
The namespace for a generated folder can be specified in the `StaticResourceFolder` item in the .csproj.

`<StaticResourceFolder Include="data/Example" Namespace="MyProject.Data"/>`
or
`<StaticResourceFolder Include="data/Example" Namespace="$(RootNamespace).Data"/>`

To use the default root namespace defined by the project.
