### ISSUE TITLE
The build breaks in VS Code

### ISSUE THREAD

**Issue by rezanid** [MarkPflug/Sylvan.BuildTools.Resources#22]
Thanks for the great job creating this useful nugget package! Today when I tried to build my project from VS Code instead of VS, I wan't able to. I get build time errors as if your code-get did not work and get errors like the following.

The name 'Resources' does not exist in the current context[CS0103](https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS0103%29)

Have you ever tested in VS Code?

I have this in my csproj file:
```xml
  <ItemGroup>
    <JsonResource Update="Resources.resj">
      <AccessModifier>Public</AccessModifier>
      <Namespace>PSDataverse</Namespace>
      <ResourceName>Resources</ResourceName>
    </JsonResource>
  </ItemGroup>
```

also the following:
```xml
  <ItemGroup>
    <JsonResource Remove="Resources.resj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources.resj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources.resj" />
  </ItemGroup>
```

Not sure what's happening there.

**Comment by rezanid** [comment]
It turned out that these lines were added to the csproj file that broke the build. It's not clear what caused this. But, removing them fixed the problem.
```xml
  <ItemGroup>
    <JsonResource Remove="Resources.resj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources.resj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources.resj" />
  </ItemGroup>
```

**Comment by MarkPflug** [comment]
Yeah, this is kind-of a known issue. There is something in Visual Studio (not Code) that will modify the .csproj when you add these files. I don't understand what exactly causes it, nor how to fix it.

I still have this as an open issue, in fact: https://github.com/MarkPflug/Sylvan.BuildTools.Resources/issues/9
