### ISSUE TITLE
where to find the generated resource class?

### ISSUE THREAD

**Issue by fabianus76** [MarkPflug/Sylvan.BuildTools.Resources#8]
Hi Mark, this is a really valuable package !

I added a Resources.resj and a Resources.de.resj and a Resources.fr.resj file in a folder named Resources and the compilation works fine - the following dlls are generated: 
- \bin\MyProject.resources.dll
- \bin\de\MyProject.resources.dll
- \bin\fr\MyProject.resources.dll

But I can not find the generated classes. There is no namespaces MyProject.Resources. Could you precise how the generated classes are named and the namespace where they are placed?

Perhaps (probably) I am not knowledgeable enough. I would like to inject IStringLocalizer with the resource class generated by you. 

Thanks a lot for any feedback !

**Comment by MarkPflug** [comment]
What development environment are you using? I'm going to assume VS Code.

In Visual Studio, this package uses a special capability that will generate and include the classes as design time, before you even build the code.

In VS Code, however it appears that mechanism doesn't exist in the same way, so while the project should build correctly (`dotnet build` from the command line should report no issues), the Resources class and it's members won't appear in autocomplete listings, and will appear as an error in VSCode. I've found that you can trigger them to appear by opening the .csproj and saving it. You don't even need to edit it, just save it. This seems to cause the IDE to run the part of the build process that triggers the code generation and includes the classes.

You should be able to find the generated code files under the /obj/(debug|release)/(targetframework) folder, named something like Resources.resj.g.cs.
